### ISSUE TITLE
Using battery Icon

### ISSUE THREAD

**Issue by Thermatix** [tmux-plugins/tmux-battery#26] opened 2016-07-28 08:56 UTC
I'm not sure if this is a bug or not.
When my mac is charging it displays the lightning bolt icon, when it's full it displays a battery icon, when it's using the battery, it displays nothing, shouldn't there be a 'on battery power' icon?

p.s. this is an awesome plugin, I love having a status bar at the bottom of my terminal, with battery power in it, sooo useful.

**Comment by edouard-lopez** [comment] 2016-09-29 09:38
see #27

**Comment by martinbeentjes** [comment] 2016-09-29 09:42
Duplicate of #27.

**Closed by martinbeentjes** 2016-09-29 09:42 UTC
Labels: duplicate
